using System.Process.Domain.Constants;
using System.Process.Domain.ValueObjects;
using System.Process.Infrastructure.Adapters;
using System.Proxy.Feedzai.TransferInitiation.Messages;
using System;

namespace System.Process.Application.Commands.TransferMoney.Adapters
{
    public class TransferInitiationAdapter : IAdapter<TransferInitiationParams, TransferMoneyRequest>
    {
        #region Properties

        private ProcessConfig ProcessConfig { get; set; }

        #endregion

        #region Constructor
        public TransferInitiationAdapter(ProcessConfig ProcessConfig)
        {
            ProcessConfig = ProcessConfig;
        }
        #endregion

        #region IAdapter implementation
        public TransferInitiationParams Adapt(TransferMoneyRequest input)
        {
            return new TransferInitiationParams
            {
                ReceiverName = string.Empty,
                SenderName = string.Empty,
                SenderBankCountryCode = Constants.US,
                SenderStreetAddr = string.Empty,
                SenderCountryCode = string.Empty,
                ReceiverId = string.Empty,
                SenderId = input.SystemId,

                ReceiverCountryCode = string.Empty,
                ReceiverStreetAddr = string.Empty,
                ReceiverBankCountryCode = string.Empty,
                DeviceIpAddressLocation = string.Empty,

                EventOccurredAt = DateTimeOffset.UtcNow.ToUnixTimeMilliseconds(),
                CreatedAt = DateTimeOffset.UtcNow.ToUnixTimeMilliseconds(),
                SenderTransactionBankAccountNumber = input.AccountFrom.FromAccountNumber,
                SenderAccountType = input.AccountFrom.FromAccountType,
                ReceiverTransactionBankAccountNumber = input.AccountTo.ToAccountNumber,
                ReceiverAccountType = input.AccountTo.ToAccountType,
                SenderTransactionAmount = Convert.ToInt64(input.Amount * 100),
                PaymentType = ProcessConfig.TransferConfig.XferPaymentType,
                Direction = ProcessConfig.TransferConfig.XferDirection,
                SystemId = input.SystemId,
                SenderBankRoutingNumber = ProcessConfig.SenderBankRoutingNumber,
                ReceiverBankRoutingNumber = ProcessConfig.ReceiverBankRoutingNumber,
                CoreTransactionDebitCode = string.Empty,
                CoreTransactionCreditCode = string.Empty,
                SenderTransactionCurrency = ProcessConfig.SenderTransactionCurrency,
                SenderTransactionNotes = string.Empty,
                PaymentSubType = ProcessConfig.TransferConfig.XferPaymentSubType,

                ReceiverEmail = string.Empty,
                ReceiverPhone = string.Empty,
                SenderTransactionFeeAmount = 0,

                ReceiverBankName = string.Empty,
                ReceiverBankPostalCode = string.Empty,
                ReceiverBankAddress = string.Empty,
                ReceiverBankCity = string.Empty,
                ReceiverCity = string.Empty,
                ReceiverZip = string.Empty,

                ReceiverBankFeeType = ProcessConfig.TransferConfig.ReceiverBankFeeType,
                SenderProcesstatus = ProcessConfig.TransferConfig.SenderProcesstatus,
                Frequency = ProcessConfig.TransferConfig.Frequency,
                SenderCorrespondentBankFeeType = ProcessConfig.TransferConfig.SenderCorrespondentBankFeeType,
                ReceiverTransactionFeeType = ProcessConfig.TransferConfig.ReceiverTransactionFeeType,
                GeographicScope = ProcessConfig.TransferConfig.GeographicScope,
                ReceiverCorrespondentBankFeeType = ProcessConfig.TransferConfig.ReceiverCorrespondentBankFeeType,
                SenderTransactionFeeType = ProcessConfig.TransferConfig.SenderTransactionFeeType,
                ReceiverProcesstatus = ProcessConfig.TransferConfig.ReceiverProcesstatus,
                ChannelType = ProcessConfig.TransferConfig.ChannelType,
                SenderBankFeeType = ProcessConfig.TransferConfig.SenderBankFeeType,
                PaymentStatus = ProcessConfig.TransferConfig.PaymentStatus,

                DeviceId = string.Empty,
                DeviceType = string.Empty,
                DeviceOperatingSystem = string.Empty,
                DeviceIpAddress = string.Empty,
                DeviceLongitude = string.Empty,
                DeviceLatitude = string.Empty,
                UserEmailAddress = string.Empty,
                UserPhoneNumber = string.Empty,
                UserPhoneNumberCountryCode = string.Empty,
                LoginSessionId = string.Empty,
                UserId = string.Empty,

                EventExternalId = Guid.NewGuid().ToString(),
                LifecycleId = Guid.NewGuid().ToString(),
                BulkId = string.Empty,
                DdMandateName = string.Empty,
                DdMandateNumber = string.Empty,
                ProductCode = string.Empty,
                CutoffAt = 0,
                SenderInitiatedAt = 0,
                SenderUrgency = false,
                RequestedExecutionAt = 0,
                ExecutionAt = 0,
                NumberOfPayments = 0,
                RecurringPayment = false,
                RecurringPaymentDay = 0,
                RecurringPaymentHour = 0,
                PaymentReference = string.Empty,
                EndToEndIdentification = string.Empty,
                SenderSegment = string.Empty,
                SenderEmail = string.Empty,
                SenderPhone = string.Empty,
                SenderPhoneValCode = string.Empty,
                SenderCitizenIdNumber = string.Empty,
                SenderPassportNumber = string.Empty,
                SenderDriverLicense = string.Empty,
                SenderSsn = string.Empty,
                SenderTaxNumber = string.Empty,
                SenderRegistrationDate = 0,
                SenderZip = string.Empty,
                SenderRegion = string.Empty,
                SenderDob = string.Empty,
                SenderNumberOfCards = 0,
                SenderNumberOfProcess = 0,
                SenderTotalBalance = 0,
                SenderTotalCreditLimit = 0,
                SenderKycLvl = string.Empty,
                SenderOccupation = string.Empty,
                SenderOccupationStatus = string.Empty,
                SenderRiskRating = string.Empty,
                SenderCurrency = string.Empty,
                SenderCity = string.Empty,
                SenderAccountIban = string.Empty,
                SenderAccountBic = string.Empty,
                SenderAccountOpenDate = 0,
                SenderAccountCurrency = string.Empty,
                SenderAccountBalance = 0,
                SenderAccountCreditLimit = 0,
                SenderAccountOtbLimit = 0,
                SenderAccountAvailableCredit = 0,
                SenderAccountDebtBalance = 0,
                SenderAccountCashAdvanceBalance = 0,
                SenderAccountLastActivity = 0,
                SenderAccountLastPaymentDate = 0,
                SenderAccountLastPaymentAmount = 0,
                SenderAccountPwChangeFlag = false,
                SenderAccountRewardsUsedCount = 0,
                SenderAccountDebtPaymentMethod = string.Empty,
                SenderAccountNumberOfCards = 0,
                SenderAccountAtc1 = string.Empty,
                SenderAccountAtc2 = string.Empty,
                SenderTransactionForeignExchangeRate = 0,
                SenderTransactionFeeCurrency = string.Empty,
                SenderTransactionCategoryPurpose = string.Empty,
                SenderTransactionPurpose = string.Empty,
                SenderBankBic = string.Empty,
                SenderBankSortCode = string.Empty,
                SenderBankBranchId = string.Empty,
                SenderBankName = string.Empty,
                SenderBankPostalCode = string.Empty,
                SenderBankAddress = string.Empty,
                SenderBankCity = string.Empty,
                SenderBankCurrency = string.Empty,
                SenderBankForeignExchangeRate = 0,
                SenderBankFeeAmount = 0,
                SenderBankFeeCurrency = string.Empty,
                SenderCorrespondentBankBic = string.Empty,
                SenderCorrespondentBankName = string.Empty,
                SenderCorrespondentBankPostalCode = string.Empty,
                SenderCorrespondentBankAddress = string.Empty,
                SenderCorrespondentBankCity = string.Empty,
                SenderCorrespondentBankCountryCode = string.Empty,
                SenderCorrespondentBankCurrency = string.Empty,
                SenderCorrespondentBankForeignExchangeRate = 0,
                SenderCorrespondentBankFeeAmount = 0,
                SenderCorrespondentBankFeeCurrency = string.Empty,
                ReceiverCorrespondentBankBic = string.Empty,
                ReceiverCorrespondentBankName = string.Empty,
                ReceiverCorrespondentBankPostalCode = string.Empty,
                ReceiverCorrespondentBankAddress = string.Empty,
                ReceiverCorrespondentBankCity = string.Empty,
                ReceiverCorrespondentBankCountryCode = string.Empty,
                ReceiverCorrespondentBankCurrency = string.Empty,
                ReceiverCorrespondentBankForeignExchangeRate = 0,
                ReceiverCorrespondentBankFeeAmount = 0,
                ReceiverCorrespondentBankFeeCurrency = string.Empty,
                ReceiverBankBic = string.Empty,
                ReceiverBankSortCode = string.Empty,
                ReceiverBankBranchId = string.Empty,
                ReceiverBankCurrency = string.Empty,
                ReceiverBankForeignExchangeRate = 0,
                ReceiverBankFeeAmount = 0,
                ReceiverBankFeeCurrency = string.Empty,
                ReceiverTransactionAmount = 0,
                ReceiverTransactionCurrency = string.Empty,
                ReceiverTransactionForeignExchangeRate = 0,
                ReceiverTransactionFeeAmount = 0,
                ReceiverTransactionFeeCurrency = string.Empty,
                ReceiverSettlementAt = 0,
                ReceiverTransactionNotes = string.Empty,
                ReceiverSegment = string.Empty,
                ReceiverPhoneValCode = string.Empty,
                ReceiverCitizenIdNumber = string.Empty,
                ReceiverPassportNumber = string.Empty,
                ReceiverDriverLicense = string.Empty,
                ReceiverSsn = string.Empty,
                ReceiverTaxNumber = string.Empty,
                ReceiverRegistrationDate = 0,
                ReceiverRegion = string.Empty,
                ReceiverDob = string.Empty,
                ReceiverNumberOfCards = 0,
                ReceiverNumberOfProcess = 0,
                ReceiverTotalBalance = 0,
                ReceiverTotalCreditLimit = 0,
                ReceiverKycLvl = string.Empty,
                ReceiverOccupation = string.Empty,
                ReceiverOccupationStatus = string.Empty,
                ReceiverRiskRating = string.Empty,
                ReceiverCurrency = string.Empty,
                ReceiverAccountIban = string.Empty,
                ReceiverAccountBic = string.Empty,
                ReceiverAccountOpenDate = 0,
                ReceiverAccountCurrency = string.Empty,
                ReceiverAccountBalance = 0,
                ReceiverAccountCreditLimit = 0,
                ReceiverAccountOtbLimit = 0,
                ReceiverAccountAvailableCredit = 0,
                ReceiverAccountDebtBalance = 0,
                ReceiverAccountCashAdvanceBalance = 0,
                ReceiverAccountLastActivity = 0,
                ReceiverAccountLastPaymentDate = 0,
                ReceiverAccountLastPaymentAmount = 0,
                ReceiverAccountPwChangeFlag = false,
                ReceiverAccountRewardsUsedCount = 0,
                ReceiverAccountDebtPaymentMethod = string.Empty,
                ReceiverAccountNumberOfCards = 0,
                ReceiverAccountAtc1 = string.Empty,
                ReceiverAccountAtc2 = string.Empty,
                PassReset = false,
                ChallengeRiskScore = 0,
                ChallengeRiskFlag = false,
                ScaRiskScore = 0,
                ScaRiskFlag = false,
                NumberOfAuthentications = 0,
                MaxNumberOfAuthentications = 0,
                ApprovalTotalApproves = 0,
                ApprovalFinalApproval = false,
                ApprovalSignaturesApplied = 0,
                ApprovalCurrentNumber = 0,
                ApprovalPrimaryAdmin = false,
                ApprovalSubmittedAt = 0,
                ApprovalType = string.Empty,
                ApprovalStatus = string.Empty,
                ApproverLoginId = string.Empty,
                ApproverCustomerId = string.Empty,
                ApproverType = string.Empty
            };
        }
        #endregion
    }
}