using System;
using System.Linq;
using System.Process.Domain.ValueObjects;
using System.Process.Infrastructure.Adapters;
using System.Proxy.Feedzai.TransferInitiation.Messages;
using System.Proxy.RdaAdmin.GetProcessCriteriaReference.Messages;
using System.Proxy.RdaAdmin.Messages;

namespace System.Process.Application.Commands.RemoteDepositCapture.Adapters
{
    public class TransferInitiationAdapter : IAdapter<TransferInitiationParams, RemoteDepositCaptureRequest>
    {
        #region Properties
        private AdminBaseResult<GetProcessCriteriaReferenceResponse> Process { get; set; }
        private ProcessConfig ProcessConfig { get; set; }

        #endregion

        #region Constructor

        public TransferInitiationAdapter(
            AdminBaseResult<GetProcessCriteriaReferenceResponse> Process,
            ProcessConfig ProcessConfig
            )
        {
            Process = Process;
            ProcessConfig = ProcessConfig;
        }

        #endregion

        public TransferInitiationParams Adapt(RemoteDepositCaptureRequest input)
        {
            return new TransferInitiationParams
            {
                ReceiverName = string.Empty,
                ReceiverCountryCode = string.Empty,
                ReceiverStreetAddr = string.Empty,
                ReceiverId = input.SystemId,


                SenderName = string.Empty,
                SenderCountryCode = string.Empty,
                SenderStreetAddr = string.Empty,
                SenderBankCountryCode = string.Empty,
                ReceiverBankCountryCode = string.Empty,
                SenderId = string.Empty,
                DeviceIpAddressLocation = string.Empty,


                EventOccurredAt = (long)DateTime.UtcNow.Subtract(new DateTime(1970, 1, 1)).TotalMilliseconds,
                CreatedAt = (long)DateTime.UtcNow.Subtract(new DateTime(1970, 1, 1)).TotalMilliseconds,
                SystemId = input.SystemId,
                Direction = ProcessConfig.TransferConfig.RdcDirection,
                ReceiverAccountType = Process.Result.Process.First().Type.ToString(),
                ReceiverTransactionBankAccountNumber = Process.Result.Process.First().AccountNumber,
                ReceiverBankRoutingNumber = Process.Result.Process.First().RoutingNumber,
                SenderTransactionAmount = Convert.ToInt64(input.TotalAmount * 100),
                SenderTransactionCurrency = string.Empty,
                SenderTransactionNotes = string.Empty,
                DeviceId = string.Empty,
                DeviceType = string.Empty,
                DeviceOperatingSystem = string.Empty,
                DeviceIpAddress = string.Empty,
                DeviceLongitude = string.Empty,
                DeviceLatitude = string.Empty,
                UserEmailAddress = string.Empty,
                UserPhoneNumber = string.Empty,
                UserPhoneNumberCountryCode = string.Empty,
                LoginSessionId = string.Empty,
                UserId = string.Empty,                

                SenderTransactionBankAccountNumber = string.Empty,
                SenderAccountType = string.Empty,
                SenderBankRoutingNumber = string.Empty,

                PaymentType = ProcessConfig.TransferConfig.RdcPaymentType,
                PaymentSubType = ProcessConfig.TransferConfig.RdcPaymentSubType,

                CoreTransactionDebitCode = string.Empty,
                CoreTransactionCreditCode = string.Empty,

                SenderTransactionFeeAmount = 0,
                ReceiverEmail = string.Empty,
                ReceiverPhone = string.Empty,

                ReceiverBankName = string.Empty,
                ReceiverBankPostalCode = string.Empty,
                ReceiverBankAddress = string.Empty,
                ReceiverBankCity = string.Empty,
                ReceiverCity = string.Empty,
                ReceiverZip = string.Empty,

                ReceiverBankFeeType = ProcessConfig.TransferConfig.ReceiverBankFeeType,
                SenderProcesstatus = ProcessConfig.TransferConfig.SenderProcesstatus,
                Frequency = ProcessConfig.TransferConfig.Frequency,
                SenderCorrespondentBankFeeType = ProcessConfig.TransferConfig.SenderCorrespondentBankFeeType,
                ReceiverTransactionFeeType = ProcessConfig.TransferConfig.ReceiverTransactionFeeType,
                GeographicScope = ProcessConfig.TransferConfig.GeographicScope,
                ReceiverCorrespondentBankFeeType = ProcessConfig.TransferConfig.ReceiverCorrespondentBankFeeType,
                SenderTransactionFeeType = ProcessConfig.TransferConfig.SenderTransactionFeeType,
                ReceiverProcesstatus = ProcessConfig.TransferConfig.ReceiverProcesstatus,
                ChannelType = ProcessConfig.TransferConfig.ChannelType,
                SenderBankFeeType = ProcessConfig.TransferConfig.SenderBankFeeType,
                PaymentStatus = ProcessConfig.TransferConfig.PaymentStatus,

                EventExternalId = Guid.NewGuid().ToString(),
                LifecycleId = string.Empty,
                BulkId = string.Empty,
                DdMandateName = string.Empty,
                DdMandateNumber = string.Empty,
                ProductCode = string.Empty,
                CutoffAt = 0,
                SenderInitiatedAt = 0,
                SenderUrgency = false,
                RequestedExecutionAt = 0,
                ExecutionAt = 0,
                NumberOfPayments = 0,
                RecurringPayment = false,
                RecurringPaymentDay = 0,
                RecurringPaymentHour = 0,
                PaymentReference = string.Empty,
                EndToEndIdentification = string.Empty,
                SenderSegment = string.Empty,
                SenderEmail = string.Empty,
                SenderPhone = string.Empty,
                SenderPhoneValCode = string.Empty,
                SenderCitizenIdNumber = string.Empty,
                SenderPassportNumber = string.Empty,
                SenderDriverLicense = string.Empty,
                SenderSsn = string.Empty,
                SenderTaxNumber = string.Empty,
                SenderRegistrationDate = 0,
                SenderZip = string.Empty,
                SenderRegion = string.Empty,
                SenderDob = string.Empty,
                SenderNumberOfCards = 0,
                SenderNumberOfProcess = 0,
                SenderTotalBalance = 0,
                SenderTotalCreditLimit = 0,
                SenderKycLvl = string.Empty,
                SenderOccupation = string.Empty,
                SenderOccupationStatus = string.Empty,
                SenderRiskRating = string.Empty,
                SenderCurrency = string.Empty,
                SenderCity = string.Empty,
                SenderAccountIban = string.Empty,
                SenderAccountBic = string.Empty,
                SenderAccountOpenDate = 0,
                SenderAccountCurrency = string.Empty,
                SenderAccountBalance = 0,
                SenderAccountCreditLimit = 0,
                SenderAccountOtbLimit = 0,
                SenderAccountAvailableCredit = 0,
                SenderAccountDebtBalance = 0,
                SenderAccountCashAdvanceBalance = 0,
                SenderAccountLastActivity = 0,
                SenderAccountLastPaymentDate = 0,
                SenderAccountLastPaymentAmount = 0,
                SenderAccountPwChangeFlag = false,
                SenderAccountRewardsUsedCount = 0,
                SenderAccountDebtPaymentMethod = string.Empty,
                SenderAccountNumberOfCards = 0,
                SenderAccountAtc1 = string.Empty,
                SenderAccountAtc2 = string.Empty,
                SenderTransactionForeignExchangeRate = 0,
                SenderTransactionFeeCurrency = string.Empty,
                SenderTransactionCategoryPurpose = string.Empty,
                SenderTransactionPurpose = string.Empty,
                SenderBankBic = string.Empty,
                SenderBankSortCode = string.Empty,
                SenderBankBranchId = string.Empty,
                SenderBankName = string.Empty,
                SenderBankPostalCode = string.Empty,
                SenderBankAddress = string.Empty,
                SenderBankCity = string.Empty,
                SenderBankCurrency = string.Empty,
                SenderBankForeignExchangeRate = 0,
                SenderBankFeeAmount = 0,
                SenderBankFeeCurrency = string.Empty,
                SenderCorrespondentBankBic = string.Empty,
                SenderCorrespondentBankName = string.Empty,
                SenderCorrespondentBankPostalCode = string.Empty,
                SenderCorrespondentBankAddress = string.Empty,
                SenderCorrespondentBankCity = string.Empty,
                SenderCorrespondentBankCountryCode = string.Empty,
                SenderCorrespondentBankCurrency = string.Empty,
                SenderCorrespondentBankForeignExchangeRate = 0,
                SenderCorrespondentBankFeeAmount = 0,
                SenderCorrespondentBankFeeCurrency = string.Empty,
                ReceiverCorrespondentBankBic = string.Empty,
                ReceiverCorrespondentBankName = string.Empty,
                ReceiverCorrespondentBankPostalCode = string.Empty,
                ReceiverCorrespondentBankAddress = string.Empty,
                ReceiverCorrespondentBankCity = string.Empty,
                ReceiverCorrespondentBankCountryCode = string.Empty,
                ReceiverCorrespondentBankCurrency = string.Empty,
                ReceiverCorrespondentBankForeignExchangeRate = 0,
                ReceiverCorrespondentBankFeeAmount = 0,
                ReceiverCorrespondentBankFeeCurrency = string.Empty,
                ReceiverBankBic = string.Empty,
                ReceiverBankSortCode = string.Empty,
                ReceiverBankBranchId = string.Empty,
                ReceiverBankCurrency = string.Empty,
                ReceiverBankForeignExchangeRate = 0,
                ReceiverBankFeeAmount = 0,
                ReceiverBankFeeCurrency = string.Empty,
                ReceiverTransactionAmount = 0,
                ReceiverTransactionCurrency = string.Empty,
                ReceiverTransactionForeignExchangeRate = 0,
                ReceiverTransactionFeeAmount = 0,
                ReceiverTransactionFeeCurrency = string.Empty,
                ReceiverSettlementAt = 0,
                ReceiverTransactionNotes = string.Empty,
                ReceiverSegment = string.Empty,
                ReceiverPhoneValCode = string.Empty,
                ReceiverCitizenIdNumber = string.Empty,
                ReceiverPassportNumber = string.Empty,
                ReceiverDriverLicense = string.Empty,
                ReceiverSsn = string.Empty,
                ReceiverTaxNumber = string.Empty,
                ReceiverRegistrationDate = 0,
                ReceiverRegion = string.Empty,
                ReceiverDob = string.Empty,
                ReceiverNumberOfCards = 0,
                ReceiverNumberOfProcess = 0,
                ReceiverTotalBalance = 0,
                ReceiverTotalCreditLimit = 0,
                ReceiverKycLvl = string.Empty,
                ReceiverOccupation = string.Empty,
                ReceiverOccupationStatus = string.Empty,
                ReceiverRiskRating = string.Empty,
                ReceiverCurrency = string.Empty,
                ReceiverAccountIban = string.Empty,
                ReceiverAccountBic = string.Empty,
                ReceiverAccountOpenDate = 0,
                ReceiverAccountCurrency = string.Empty,
                ReceiverAccountBalance = 0,
                ReceiverAccountCreditLimit = 0,
                ReceiverAccountOtbLimit = 0,
                ReceiverAccountAvailableCredit = 0,
                ReceiverAccountDebtBalance = 0,
                ReceiverAccountCashAdvanceBalance = 0,
                ReceiverAccountLastActivity = 0,
                ReceiverAccountLastPaymentDate = 0,
                ReceiverAccountLastPaymentAmount = 0,
                ReceiverAccountPwChangeFlag = false,
                ReceiverAccountRewardsUsedCount = 0,
                ReceiverAccountDebtPaymentMethod = string.Empty,
                ReceiverAccountNumberOfCards = 0,
                ReceiverAccountAtc1 = string.Empty,
                ReceiverAccountAtc2 = string.Empty,
                PassReset = false,
                ChallengeRiskScore = 0,
                ChallengeRiskFlag = false,
                ScaRiskScore = 0,
                ScaRiskFlag = false,
                NumberOfAuthentications = 0,
                MaxNumberOfAuthentications = 0,
                ApprovalTotalApproves = 0,
                ApprovalFinalApproval = false,
                ApprovalSignaturesApplied = 0,
                ApprovalCurrentNumber = 0,
                ApprovalPrimaryAdmin = false,
                ApprovalSubmittedAt = 0,
                ApprovalType = string.Empty,
                ApprovalStatus = string.Empty,
                ApproverLoginId = string.Empty,
                ApproverCustomerId = string.Empty,
                ApproverType = string.Empty
            };
        }
    }
}
