namespace System.Process.Domain.ValueObjects
{
    public class ProcessConfig
    {
        public string AdapterProductCode { get; set; }
        public string AdapterBranchCode { get; set; }
        public string AccountCommandProductCode { get; set; }
        public string AccountCommandBranchCode { get; set; }
        public string AccountType { get; set; }
        public string AccountClassificationCode { get; set; }
        public string QuantityOfNumberProcess { get; set; }
        public string OfficerCode { get; set; }
        public string ChargeODCode { get; set; }
        public string ServiceChargeWaived { get; set; }
        public string SignatureVerificationCode { get; set; }
        public string IncludeCombinedStatement { get; set; }
        public string ItemTruncation { get; set; }
        public string ImagePrintCheckOrderCode { get; set; }
        public string StatementFrequency { get; set; }
        public string StatementFrequencyCode { get; set; }
        public string StatementPrintCode { get; set; }
        public string StatementServiceCharge { get; set; }
        public string AllowReDepositCode { get; set; }
        public string RedepositNoticeCode { get; set; }
        public string NumberAllowedRedepositItems { get; set; }
        public string CheckGuaranty { get; set; }
        public string ATMCard { get; set; }
        public string CloseOnZeroBalance { get; set; }
        public string HighVolumeAccountCode { get; set; }
        public string LstPostAccountCode { get; set; }
        public string DebitTransactionCodeCode { get; set; }
        public string TransactionCodeCode { get; set; }
        public string RoutingNumber { get; set; }
        public string CurrentBalanceCurrency { get; set; }
        public string AvailableBalanceCurrency { get; set; }
        public string TransferTypeACH { get; set; }
        public string CardActivationStatus { get; set; }
        public string CardOrderFlagHostValue { get; set; }
        public string CardOrderStatusFlagHostValue { get; set; }
        public string CardOrderTypeHostValue { get; set; }
        public string CardReissueIndicator { get; set; }
        public string FlatCardInd { get; set; }
        public string PhotoId { get; set; }
        public string ActivationFlag { get; set; }
        public string AddressType { get; set; }
        public string MemberNumber { get; set; }
        public string MemberNumberReplaceCard { get; set; }        
        public string Bin { get; set; }
        public string LimitGroup { get; set; }
        public string CanWithdraw { get; set; }
        public string CanDeposit { get; set; }
        public string CanInquire { get; set; }
        public string PaymentsTo { get; set; }
        public string PaymentsFrom { get; set; }
        public string TransfersTo { get; set; }
        public string TransfersFrom { get; set; }
        public string CanPurchase { get; set; }
        public string ThirdPartyPymt { get; set; }
        public string CardMediaTypeHostValue { get; set; }
        public string CardAssociationHostValue { get; set; }
        public string CardTypeHostValue { get; set; }
        public string CardSubTypeHostValue { get; set; }
        public string CardCategoryHostValue { get; set; }
        public string HasCardCompanionMini { get; set; }
        public string HasCardCompanionMicro { get; set; }
        public string HasCardCompanionMobile { get; set; }
        public string PinOffsetIndicator { get; set; }
        public string PinOffset { get; set; }
        public string AvsData { get; set; }
        public string OptOutVauAbuFlag { get; set; }
        public string ServiceCodeHostValue { get; set; }
        public string AutoIssueInd { get; set; }
        public string ContactPrefHostValue { get; set; }
        public string CreditLimit { get; set; }
        public string CashLimit { get; set; }
        public string PwrOfAttrnyFlag { get; set; }
        public string TravelIndHostValue { get; set; }
        public string AddressTypeHostValue { get; set; }
        public string AddressFormatHostValue { get; set; }
        public string IsPrimaryContact { get; set; }
        public string CardOrdFlagHostValue { get; set; }
        public string CardOrdStatFlagHostValue { get; set; }
        public string CardOrdTypeHostValue { get; set; }
        public string CardReplInd { get; set; }
        public string LanguageIndHostValue { get; set; }
        public string FirstCallInd { get; set; }
        public string AccountTypeHostValue { get; set; }
        public string PrimaryIndicator { get; set; }
        public string FundingIndicator { get; set; }
        public string Processtatus { get; set; }
        public string ProcesstatusHostValue { get; set; }
        public string CanAccountWithdraw { get; set; }
        public string CanAccountDeposit { get; set; }
        public string CanAccountInquiry { get; set; }
        public string PaymentsToAccount { get; set; }
        public string PaymentsFromAccount { get; set; }
        public string TransferToAccount { get; set; }
        public string TransferFromAccount { get; set; }
        public string CanAccountPurchase { get; set; }
        public string EnterpriseCustomerId { get; set; }
        public string ActivationStatus { get; set; }
        public string OarSelectType { get; set; }
        public string AccountBalance { get; set; }
        public string Locked { get; set; }
        public string TemplateCreated { get; set; }
        public string FeeAmount { get; set; }
        public CardStatus CardStatus { get; set; }
        public string SenderBankRoutingNumber { get; set; }
        public string ReceiverBankRoutingNumber { get; set; }
        public string SenderTransactionCurrency { get; set; }
        public string SafraBankingAccountType { get; set; }
        public string SafraDigitalBank { get; set; }
        public string AchDebitTransactionCodeCode { get; set; }
        public int AchTermCount { get; set; }
        public string AchTermUnits { get; set; }
        public string AchCreditTransactionCodeCode { get; set; }
        public int AchFeeAmount { get; set; }
        public string AchSendPreNoteCode { get; set; }
        public string AchOneTime { get; set; }
        public string AchUseLoanDateCode { get; set; }
        public string AchUseLoanAmountCode { get; set; }
        public string AchNsfCode { get; set; }
        public string WireAnlysCode { get; set; }
        public string TransferSourceType { get; set; }
        public string BalanceInquiryAplication { get; set; }
        public string EncryptKey { get; set; }
        public TransferConfig TransferConfig { get; set; }
        public RtdxParamsConfig RtdxParamsConfig { get; set; }
        public string CompanyName { get; set; }
        public string CompanyId { get; set; }
        public string CreditCardActivationStatus { get; set; }
        public bool ShouldDisableJwtValidation { get; set; }
    }
}